server:
  port: 7003
  servlet:
    context-path: /devUtilApi
spring:
  application:
    name: devUtilApi
  security:
    cors:
      serverSupportAll: true
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 800ms # 连接超时时间（毫秒）
  datasource:
    password: 123456-abc
    username: root
    url: jdbc:mysql://localhost:3306/dev_utils?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
